gestor/urls.py
from django.urls import path
from . import views
from .views import calendario_reservas
from .views import calendario_reservas_materiais
from .views import reservas_materiais
from .views import reservas_salas
from .views import SalaListView, SalaCreateView, SalaUpdateView, SalaDetailView, SalaDeleteView
from .views import MaterialListView, MaterialCreateView, MaterialUpdateView, MaterialDetailView, MaterialDeleteView
from .views import RankingSalasView, RankingMateriaisView
from .views import UsuarioListView

app_name = 'gestor'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('gestor_ver_salas/', views.gestor_ver_salas, name='gestor_ver_salas'),
    path('gestor_ver_materiais/', views.gestor_ver_materiais, name='gestor_ver_materiais'),
    path('calendario_reservas/', calendario_reservas, name='calendario_reservas'),
    path('calendario_reservas_materiais/', calendario_reservas_materiais, name='calendario_reservas_materiais'),
    path('reservas_materiais/', reservas_materiais, name='reservas_materiais'),
    path('reservas_salas/', reservas_salas, name='reservas_salas'),
    path('salas/', SalaListView.as_view(), name='sala_list'),
    path('salas/nova/', SalaCreateView.as_view(), name='sala_create'),
    path('salas/<int:pk>/editar/', SalaUpdateView.as_view(), name='sala_edit'),
    path('salas/<int:pk>/detail/', SalaDetailView.as_view(), name='sala_detail'),
    path('salas/<int:pk>/excluir/', SalaDeleteView.as_view(), name='sala_delete'),
    path('materiais/', MaterialListView.as_view(), name='material_list'),
    path('materiais/novo/', MaterialCreateView.as_view(), name='material_create'),
    path('materiais/<int:pk>/editar/', MaterialUpdateView.as_view(), name='material_edit'),
    path('materiais/<int:pk>/detalhes/', MaterialDetailView.as_view(), name='material_detail'),
    path('materiais/<int:pk>/excluir/', MaterialDeleteView.as_view(), name='material_delete'),
    # # ✅ Caminho correto para cadastro via câmera
    # path('materiais/cadastrar_camera/', views.cadastrar_material_camera, name='material_create_cam'),
    # URLs para cadastro via câmera (versão original e nova versão web)
    # URLs para cadastro via câmera (versão original e nova versão web)
    # path('materiais/cadastrar_camera/', views.cadastrar_material_camera, name='material_create_cam'),
    path('materiais/cadastrar_camera_web/', views.cadastrar_material_camera_web, name='cadastrar_material_camera_web'),

    # URLs para streaming de vídeo
    path('video_feed/', views.video_feed, name='video_feed'),
    # path('get_material_detection/', views.get_material_detection, name='get_material_detection'),



    # Novas URLs para rankings
    path('ranking_salas/', RankingSalasView.as_view(), name='ranking_salas'),
    path('ranking_materiais/', RankingMateriaisView.as_view(), name='ranking_materiais'),
    # path('usuarios_cadastrados/', views.usuarios_cadastrados, name='usuarios_cadastrados'),
    # path('usuarios_cadastrados/', views.usuarios_cadastrados, name='usuarios_cadastrados'),
    path('usuarios/', UsuarioListView.as_view(), name='usuarios_cadastrados'),
    path('usuarios/deletar/<str:usuario_id>/', views.deletar_usuario, name='deletar_usuario'),
]

salas/urls.py
from django.urls import path
from . import views

app_name = 'salas'

urlpatterns = [
    path('home/', views.home, name = 'home')
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('professor/', include('professor.urls')),
    path('salas/', include('salas.urls')),
    path('materiais/', include('materiais.urls')),
    path('gestor/', include('gestor.urls')),
]

gestor/models.py
from django.db import models

from salas.models import Salas, Reservas

from materiais.models import Materiais, Reserva

materiais/models.py
from django.db import models
from datetime import datetime, timezone
import firebase_admin
from firebase_admin import credentials, firestore
from django.forms import ValidationError
from usuarios.models import Usuario

# Inicializa o Firebase se ainda não estiver inicializado
if not firebase_admin._apps:
    cred = credentials.Certificate(
        r'C:\Users\Marcelo\Documents\GitHub\Sistema_mapeamento_laboratorio_e_materiais\sistemamapeamentolaboratorio-firebase-adminsdk-dmdt8-f79abd9e82.json'
    )
    firebase_admin.initialize_app(cred)

# Obtendo a referência do Firestore
db = firestore.client()

class Materiais(models.Model):
    nome_do_material = models.CharField(max_length=30)
    reservado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Material'

    def __str__(self):
        return self.nome_do_material

    def save(self, *args, **kwargs):
        super(Materiais, self).save(*args, **kwargs)
        # Adiciona o material à coleção 'materiais' no Firestore
        material_ref = db.collection('materiais').document(str(self.id))
        material_ref.set({
            'nome_do_material': self.nome_do_material,
            'reservado': self.reservado
        })

class Reserva(models.Model):
    usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    data_reserva = models.DateTimeField()
    data_devolucao = models.DateTimeField()
    data_solicitacao = models.DateTimeField(auto_now_add=True)
    materiais = models.ForeignKey(Materiais, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'Reserva'

    def __str__(self) -> str:
        return f"{self.usuarios} | {self.materiais}"

    def clean(self):
        # Certifique-se de que materiais, data_reserva e data_devolucao não são None
        if self.materiais is None or self.data_reserva is None or self.data_devolucao is None:
            raise ValidationError('Materiais, data de reserva e data de devolução devem ser fornecidos.')

        # Obtém a data e hora atual com fuso horário UTC
        agora = datetime.now(timezone.utc)

        # Verifica se a data de reserva é no passado
        if self.data_reserva and self.data_reserva < agora:
            raise ValidationError("A data de reserva não pode ser no passado.")

        # Verifica se já existe uma reserva para o mesmo material no mesmo horário
        conflito = Reserva.objects.filter(
            materiais=self.materiais,
            data_reserva__lt=self.data_devolucao,
            data_devolucao__gt=self.data_reserva
        ).exists()

        if conflito:
            raise ValidationError('Já existe uma reserva para este material no horário selecionado.')

    def save(self, *args, **kwargs):
        # Valida os dados antes de salvar
        self.clean()

        # Salva o objeto no banco de dados do Django
        super(Reserva, self).save(*args, **kwargs)

        # Adiciona a reserva à coleção 'reservas' no Firestore
        reserva_ref = db.collection('reserva').document(str(self.id))
        reserva_ref.set({
            'usuarios_id': self.usuarios.id,
            'data_reserva': self.data_reserva.isoformat(),  # Formato de string ISO para Firestore
            'data_devolucao': self.data_devolucao.isoformat(),
            'data_solicitacao': self.data_solicitacao.isoformat(),
            'materiais_id': self.materiais.id,
            'materiais_nome': self.materiais.nome_do_material,
        })

        # Atualiza o campo 'reservado' na coleção 'materiais' no Firestore
        material_ref = db.collection('materiais').document(str(self.materiais.id))
        material_ref.update({'reservado': True})

salas/models.py
# from django.db import models
# from datetime import date
# from usuarios.models import Usuario

# class Salas(models.Model):
#     UABJ = 'UABJ'
#     AEB = 'AEB'
#     LOCAL_CHOICES = [
#         (UABJ, 'UABJ'),
#         (AEB, 'AEB'),
#     ]

#     nome_da_sala = models.CharField(max_length=30)
#     local = models.CharField(max_length=4, choices=LOCAL_CHOICES, default=UABJ)
#     reservado = models.BooleanField(default=False)

#     class Meta:
#         verbose_name = 'Sala'

#     def __str__(self):
#         return f"{self.nome_da_sala} ({self.get_local_display()})"  # Retorna nome da sala e local formatados

# class Reservas(models.Model):
#     usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
#     data_reserva = models.DateTimeField()
#     data_devolucao = models.DateTimeField()
#     data_solicitacao = models.DateTimeField(auto_now_add=True)
#     salas = models.ForeignKey(Salas, on_delete=models.DO_NOTHING)

#     class Meta:
#         verbose_name = 'Reserva'

#     def __str__(self):
#         return f"{self.usuarios} | {self.salas}"

from django.db import models
from django.core.exceptions import ValidationError
from datetime import datetime
import pytz  # Para lidar com fuso horário
from usuarios.models import Usuario
import firebase_admin
from firebase_admin import credentials, firestore

# Inicializa o Firebase
if not firebase_admin._apps:
    cred = credentials.Certificate(
        r'C:\Users\Marcelo\Documents\GitHub\Sistema_mapeamento_laboratorio_e_materiais\sistemamapeamentolaboratorio-firebase-adminsdk-dmdt8-f79abd9e82.json'
    )
    firebase_admin.initialize_app(cred)

# Obtendo a referência do Firestore
db = firestore.client()

class Salas(models.Model):
    UABJ = 'UABJ'
    AEB = 'AEB'
    LOCAL_CHOICES = [
        (UABJ, 'UABJ'),
        (AEB, 'AEB'),
    ]

    nome_da_sala = models.CharField(max_length=30)
    local = models.CharField(max_length=4, choices=LOCAL_CHOICES, default=UABJ)
    reservado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Sala'

    def __str__(self):
        return f"{self.nome_da_sala} ({self.get_local_display()})"

    def save(self, *args, **kwargs):
        super(Salas, self).save(*args, **kwargs)

        # Atualiza ou cria o documento no Firestore
        sala_ref = db.collection('salas').document(str(self.id))
        sala_ref.set({
            'nome_da_sala': self.nome_da_sala,
            'local': self.get_local_display(),
            'reservado': self.reservado,
        })

class Reservas(models.Model):
    usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    data_reserva = models.DateTimeField()
    data_devolucao = models.DateTimeField()
    data_solicitacao = models.DateTimeField(auto_now_add=True)
    salas = models.ForeignKey(Salas, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'Reserva'

    def __str__(self):
        return f"{self.usuarios} | {self.salas}"

    def clean(self):
        if self.salas is None or self.data_reserva is None or self.data_devolucao is None:
            raise ValidationError('Salas, data de reserva e data de devolução devem ser fornecidos.')

        # Verifica se a data de reserva é no passado
        if self.data_reserva < datetime.now(pytz.utc):
            raise ValidationError("A data de reserva não pode ser no passado.")

        # Verifica se já existe uma reserva para o mesmo horário
        conflito = Reservas.objects.filter(
            salas=self.salas,
            data_reserva__lt=self.data_devolucao,
            data_devolucao__gt=self.data_reserva
        ).exists()

        if conflito:
            raise ValidationError('Já existe uma reserva para esta sala no horário selecionado.')

    def save(self, *args, **kwargs):
        # Valida os dados antes de salvar
        self.clean()

        # Salva o objeto no banco de dados do Django
        super(Reservas, self).save(*args, **kwargs)

        # Adiciona ou atualiza a reserva no Firestore
        reserva_ref = db.collection('reservas').document(str(self.id))
        reserva_ref.set({
            'usuarios_id': self.usuarios.id,
            'data_reserva': self.data_reserva.isoformat(),
            'data_devolucao': self.data_devolucao.isoformat(),
            'data_solicitacao': self.data_solicitacao.isoformat(),
            'salas_id': self.salas.id,
            'salas_nome': self.salas.nome_da_sala,
            'salas_local': self.salas.get_local_display(),
        })

        # Atualiza o campo 'reservado' na coleção de salas no Firestore
        sala_ref = db.collection('salas').document(str(self.salas.id))
        sala_ref.update({'reservado': True})

gestor/forms.py
from django import forms
from .models import Salas
from .models import Materiais

class SalaForm(forms.ModelForm):
    class Meta:
        model = Salas
        fields = ['nome_da_sala', 'local']  
        
class MaterialForm(forms.ModelForm):
    class Meta:
        model = Materiais
        fields = ['nome_do_material'] 

salas/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return HttpResponse('Olá')

gestor/templates/material_list.html
{% extends 'base.html' %}

{% block 'titulo' %}Materiais Cadastrados{% endblock %}

{% block 'conteudo' %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listando os Materiais</title>
    <style>
        /* Estilos para responsividade */
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .titulo {
            margin-bottom: 20px;
            font-size: 24px;
            text-align: center;
        }

        .lista-materiais {
            list-style-type: none;
            padding: 0;
        }

        .material-item {
            background-color: #1f3154; /* Alterando a cor de fundo */
            color: #fff; /* Alterando a cor do texto para branco */
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            display: flex;
            align-items: center;
            justify-content: space-between;
            animation: fadeIn 0.5s ease;
        }

        .material-item .acoes {
            display: flex;
            align-items: center;
        }

        .material-item .acoes a {
            margin-left: 10px;
            color: #fff; /* Cor dos ícones */
            transition: color 0.3s ease;
            text-decoration: none;
        }

        .material-item .acoes a:hover {
            color: #ccc; /* Cor ao passar o mouse */
        }

        /* Animações */
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        @keyframes slideInLeft {
            from {
                transform: translateX(-20px);
                opacity: 0;
            }
            to {
                transform: translateX(0);
                opacity: 1;
            }
        }

        /* Responsividade para telas menores */
        @media (max-width: 768px) {
            .material-item {
                flex-direction: column;
                align-items: flex-start;
            }

            .material-item .acoes {
                margin-top: 10px;
            }

            .material-item .acoes a {
                margin: 0 5px;
            }
        }

        /* Botão Cadastrar à direita */
        .btn-cadastrar {
            float: right;
            background-color: #1D2B4E; /* Azul Bootstrap */
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
            display: flex;
            align-items: center;
            margin-left: 10px;
        }

        .btn-cadastrar svg {
            fill: white;
            margin-right: 5px;
        }

        .btn-cadastrar:hover {
            background-color: #0056b3; /* Azul mais escuro Bootstrap */
        }
    </style>
</head>

<body>
    <div class="container">
        <h1 class="titulo">Materiais Cadastrados</h1>

        <button class="btn btn-primary btn-cadastrar"
                onclick="location.href = '{% url 'gestor:material_create' %}'"
                title="Cadastrar Novo Material">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
            </svg>
            Cadastrar Novo Material
        </button>

        <!-- Botão adicional: Cadastrar via Câmera -->
        <button class="btn btn-warning btn-cadastrar"
                onclick="location.href = '{% url 'gestor:cadastrar_material_camera_web' %}'"
                title="Cadastrar Material via Câmera">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-camera" viewBox="0 0 16 16">
                <path d="M10.5 2a.5.5 0 0 1 .416.223l.84 1.254H14a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5.477a2 2 0 0 1 2-2h2.243l.84-1.254A.5.5 0 0 1 5.5 2h5zM5.5 3a.5.5 0 0 1 .416.223l.84 1.254H2a1 1 0 0 0-1 1V12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5.477a1 1 0 0 0-1-1h-4.756l-.84-1.254A.5.5 0 0 1 10.5 3h-5z"/>
                <path d="M8 11.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zm0-1a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5z"/>
            </svg>
            Cadastrar via Câmera
        </button>
        <br><br>

        <ul class="lista-materiais">
            <br>
            {% for material in object_list %}
            <li class="material-item">
                <div>
                    <strong>{{ material.nome_do_material }}</strong>
                </div>
                <div class="acoes">
                    <a href="{% url 'gestor:material_edit' pk=material.id %}" class="icone"
                       style="animation: slideInLeft 0.5s ease;" title="Editar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                             class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168z"/>
                            <path d="M11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293z"/>
                        </svg>
                    </a>
                    <a href="{% url 'gestor:material_detail' pk=material.id %}" class="icone"
                       style="animation: slideInLeft 0.5s ease;" title="Visualizar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                             class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8z"/>
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5a2.5 2.5 0 0 0 0-5z"/>
                        </svg>
                    </a>
                    <a href="{% url 'gestor:material_delete' pk=material.id %}" class="icone"
                       style="animation: slideInLeft 0.5s ease;" title="Deletar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                             class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5z"/>
                            <path d="M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1z"/>
                        </svg>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>
{% endblock %}

gestor/templates/sala_list.html
{% extends 'base.html' %}

{% block 'titulo' %}Salas Cadastradas{% endblock %}

{% block 'conteudo' %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listando as Salas</title>
    <style>
        /* Estilos para responsividade */
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .titulo {
            margin-bottom: 20px;
            font-size: 24px;
            text-align: center;
        }

        .lista-salas {
            list-style-type: none;
            padding: 0;
        }

        .sala-item {
            background-color: #1f3154; /* Alterando a cor de fundo */
            color: #fff; /* Alterando a cor do texto para branco */
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            display: flex;
            align-items: center;
            justify-content: space-between;
            animation: fadeIn 0.5s ease;
        }

        .sala-item .acoes {
            display: flex;
            align-items: center;
        }

        .sala-item .acoes a {
            margin-left: 10px;
            color: #fff; /* Cor dos ícones */
            transition: color 0.3s ease;
            text-decoration: none;
        }

        .sala-item .acoes a:hover {
            color: #ccc; /* Cor ao passar o mouse */
        }

        /* Animações */
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        @keyframes slideInLeft {
            from {
                transform: translateX(-20px);
                opacity: 0;
            }
            to {
                transform: translateX(0);
                opacity: 1;
            }
        }

        /* Responsividade para telas menores */
        @media (max-width: 768px) {
            .sala-item {
                flex-direction: column;
                align-items: flex-start;
            }

            .sala-item .acoes {
                margin-top: 10px;
            }

            .sala-item .acoes a {
                margin: 0 5px;
            }
        }

        /* Botão Cadastrar à direita */
        .btn-cadastrar {
            float: right;
            background-color: #1D2B4E; /* Azul Bootstrap */
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
            display: flex;
            align-items: center;
        }

        .btn-cadastrar svg {
            fill: white;
            margin-right: 5px;
        }

        .btn-cadastrar:hover {
            background-color: #0056b3; /* Azul mais escuro Bootstrap */
        }
    </style>
</head>

<body>
    <div class="container">
        <h1 class="titulo">Salas Cadastradas</h1>

        <button class="btn btn-primary btn-cadastrar" onclick="location.href = '{% url 'gestor:sala_create' %}'"
            title="Cadastrar Nova Sala">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle"
                viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
            </svg>
            Cadastrar Nova Sala
        </button>
        <br>

        <ul class="lista-salas">
            <br>
            {% for sala in object_list %}
            <li class="sala-item">
                <div>
                    <strong>{{ sala.nome_da_sala }}</strong> - {{ sala.local }}
                </div>
                <div class="acoes">
                    <a href="{% url 'gestor:sala_edit' pk=sala.id %}" class="icone" style="animation: slideInLeft 0.5s ease;"
                        title="Editar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                            class="bi bi-pencil" viewBox="0 0 16 16">
                            <path
                                d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325" />
                        </svg>
                    </a>
                    <a href="{% url 'gestor:sala_detail' pk=sala.id %}" class="icone" style="animation: slideInLeft 0.5s ease;"
                        title="Visualizar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                            class="bi bi-eye" viewBox="0 0 16 16">
                            <path
                                d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z" />
                            <path
                                d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0" />
                        </svg>
                    </a>
                    <a href="{% url 'gestor:sala_delete' pk=sala.id %}" class="icone" style="animation: slideInLeft 0.5s ease;"
                        title="Deletar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FFFFFF"
                            class="bi bi-trash3" viewBox="0 0 16 16">
                            <path
                                d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                        </svg>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>

{% endblock %}